---
title: 'Encuesta: Relaciones entre variables'
author: "Juan Sebastian Cely"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
stopifnot(require(openxlsx), require(kableExtra), require(dm), require(dplyr), require (ggplot2), require(rms), require(caret), require(lmtest), require(car), require(yardstick), require(papaja), require(pandoc), require(tinytex), require(RColorBrewer), require(ggplotify), require(FactoMineR), require(factoextra))
knitr::opts_chunk$set(cache=F,fig.path="./figures",cache.rebuild = F, out.width = "80%")
options(knitr.table.format = "simple")
```

```{r data, include=FALSE}
wb<-loadWorkbook("020-22 Base de Datos Anonimizada V4 (1).xlsx")
names(wb)
data1 <- readWorkbook(wb,sheet=1)
codeBook1 <- readWorkbook(wb,sheet=2,skipEmptyRows = F)
```

```{r tranformación y recodificación variables, include=FALSE}
# Variables that were categorical from the beginning.
data1 <- data1 %>%
  mutate(zone = Zona,
         sex = A1,
         age_r = RANGO_EDAD,
         strat = A3,
         ethni = A5,
         edu = A6,
         kids = A9,
         ideology = A11,
         tv = B12_1,
         radio = B12_2,
         press = B12_3,
         digital = B12_4,
         social_media = B12_5,
         other_media = B12_89,
         aso_env_group = C18_7,
         clim_origin = C40,
         cont_clim = C41)

# Transform into factors
columns_to_change <- c("zone", "sex", "age_r", "strat", "ethni", "edu", "kids", "ideology", "tv", "radio", "press", "digital", "social_media", "other_media", "aso_env_group", "clim_origin", "cont_clim")
data1 <- data1 %>%
  mutate(across(all_of(columns_to_change), as.factor))

# Change the levels order and/or their names
# Variable zone where the person lives
levels(data1$zone) <- c("Rural", "Urbana")
# Variable sex
levels(data1$sex) <- c("Hombre", "Mujer")
# Variable age range
data1 <- data1 %>%
  mutate(age_r = case_when(
    age_r == 1 ~ "De 18 a 20 años",
    age_r == 2 ~ "De 21 a 24 años",
    age_r == 3 ~ "De 25 a 29 años",
    age_r == 4 ~ "De 30 a 32 años"
))
# Variable social stratum
data1 <- data1 %>%
  mutate(strat = case_when(
    strat %in% c(1,2) ~ "Bajo",
    strat %in% c(3,4) ~ "Medio",
    strat %in% c(5,6) ~ "Alto"
))
data1$strat<- factor(data1$strat, levels = c("Bajo", "Medio", "Alto"))
# Variable be part of some ethnic group or not
levels(data1$ethni) <- c("Indígena", "Gitana(o) Rrom", "Raizal", "Palenquera(o)", "Afro", "Ninguna")
data1 <- data1 %>%
  mutate(ethni = case_when(
    ethni != "Ninguna" ~ "Sí",
    ethni == "Ninguna" ~ "No"
))
# Variable university education or not
levels(data1$edu) <- c("Básica Primaria", "Básica Secundaria", "Secundaria Completa", "Técnico o Tecnólogo", "Pregrado", "Posgrado")
data1 <- data1 %>%
  mutate(edu = case_when(
    edu %in% c("Básica Primaria", "Básica Secundaria", "Secundaria Completa", "Técnico o Tecnólogo") ~ "No",
    edu %in% c("Pregrado", "Posgrado") ~ "Sí"
))
# Variable Having kids or not
levels(data1$kids) <- c("Sí", "No")
# Variable political ideology
data1 <- data1 %>%
  mutate(ideology = case_when(
    ideology %in% c(1, 2) ~ "Izquierda",
    ideology %in% c(3, 4) ~ "Centro",
    ideology %in% c(5, 6) ~ "Derecha"
  ))
# Variables related to sources of information
media <- c("tv", "radio", "press", "digital", "social_media", "other_media")
new_levels <- c("No", "Sí")
for (var in media) {
  levels(data1[[var]]) <- new_levels
}
# Variable join an environmental group
levels(data1$aso_env_group) <- c("Sí", "No")
# Variable climate change origin
data1 <- data1 %>%
  mutate(clim_origin = case_when(
    clim_origin %in% c(1,2,3,4,5) ~ "Causas naturales",
    clim_origin %in% c(6,7,8,9,10) ~ "Causas humanas"
    ))
# Variable contribution to climate change
levels(data1$cont_clim) <- c("Agricultura y ganadería", "Quema de combustibles fósiles", "Deforestación", "Volcanes y/o actividad solar")
data1 <- data1 %>%
  mutate(cont_clim = case_when(
    cont_clim %in% c(1, 3, 4) ~ "Incorrecta",
    cont_clim == 2 ~ "Correcta"
))
columns_to_change <- c("zone", "sex", "age_r", "strat", "ethni", "edu", "kids", "ideology", "tv", "radio", "press", "digital", "social_media", "other_media", "aso_env_group", "clim_origin", "cont_to_clim")
data1 <- data1 %>%
  mutate(across(all_of(columns_to_change), as.factor))
# Variables that were re coded as categorical variables
# Variable eco-anxiety
neg_emo <- c("C36_1", "C36_3", "C36_4", "C36_5", "C36_6", "C36_7", "C36_8", "C36_9", "C36_10", "C36_11", "C36_15")
amb_emo <- c("C36_13")
pos_emo <- c("C36_2", "C36_12", "C36_14", "C36_16")
data1$eco_anx <- NA
for (i in 1:nrow(data1)) {
neg_emo_count <- sum(data1[i, neg_emo] == 1)
pos_emo_count <- sum(data1[i, pos_emo] == 1)
amb_emo_count <- sum(data1[i, amb_emo] == 1)
if (neg_emo_count %in% c(1, 2) & pos_emo_count == 0 & amb_emo_count == 0) {
data1$eco_anx[i] <- "Con eco-ansiedad"
} else if (neg_emo_count == 1 & pos_emo_count == 1 & amb_emo_count == 0) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 1 & pos_emo_count == 0 & amb_emo_count == 1) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 0 & pos_emo_count == 1 & amb_emo_count == 1) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 0 & pos_emo_count == 0 & amb_emo_count == 1) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 0 & pos_emo_count %in% c(1, 2) & amb_emo_count == 0) {
data1$eco_anx[i] <- "Sin eco-ansiedad"
}
}
# Variable thoughts about climate change
pos_thought <- c("C37_9", "C37_11", "C37_12", "C37_13", "C37_15")
neg_thought<- c("C37_1", "C37_2", "C37_4", "C37_5", "C37_6", "C37_7", "C37_8", "C37_14")
neut_thought <- c("C37_3", "C37_10")
data1$thoughts <- NA
for (i in 1:nrow(data1)) {
neg_th_count <- sum(data1[i, neg_thought] == 1)
pos_th_count <- sum(data1[i, pos_thought] == 1)
amb_th_count <- sum(data1[i, neut_thought] == 1)
if (neg_th_count %in% c(1, 2, 3) & pos_th_count == 0 & amb_th_count == 0) {
data1$thoughts[i] <- "Negativos"
} else if (neg_th_count == 2 & pos_th_count == 1 & amb_th_count == 0) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 2 & pos_th_count == 0 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 1 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 1 & amb_th_count == 0) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 0 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count %in% c(1, 2, 3) & amb_th_count == 0) {
data1$thoughts[i] <- "Positivos"
} else if (neg_th_count == 1 & pos_th_count == 2 & amb_th_count == 0) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 2 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 1 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 0 & amb_th_count %in% c(1, 2)) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 0 & amb_th_count == 2) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 1 & amb_th_count == 2) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
}
}
columns_to_change2 <- c("eco_anx", "thoughts")
data1 <- data1 %>%
  mutate(across(all_of(columns_to_change), as.factor))
data1_cat <- data1 %>%
  dplyr::select("zone", "sex", "age_r", "strat", "ethni", "edu", "kids", "ideology", "tv", "radio", "press", "digital", "social_media", "other_media", "aso_env_group", "clim_origin", "cont_clim", "eco_anx", "thoughts")
```

```{r análisis de componentes múltiples}
chisq.test(data1_cat$eco_anx, data1_cat$clim_origin)
result_mca <- MCA(data1_cat, graph = TRUE)
res.mca <- MCA(data1_cat, graph = FALSE)
fviz_mca_biplot(res.mca, 
               repel = TRUE,
               ggtheme = theme_minimal())
```

# Emociones frente al cambio climático y zona de residencia

```{r relación estrato edad}
tab_est_age <- table(data1$age_r, data1$A3)
kable(round(prop.table(tab_est_age) * 100, 1), booktabs = TRUE)

custom_palette <- brewer.pal(6, "Set2")
plot_est_age <- data1 %>%
  ggplot(aes(x = strat, y = A2)) +
  geom_boxplot(aes(colour = strat)) +
  labs(x = "Estrato", y = "Edad") +
  ggtitle("Distribución \n Edad por Estrato") +
  papaja::theme_apa() +
  scale_y_continuous(breaks = seq(18, 32, 2)) +
  theme(legend.position="none") +
  scale_color_manual(values = custom_palette)
plot_est_age
```


```{r relación nivel educativo estrato}
tab_est_edu <- table(data1$A6, data1$A3)
kable(round(prop.table(tab_est_edu) * 100, 1), booktabs = TRUE)

custom_palette <- brewer.pal(6, "BrBG")
plot_est_edu <- data1 %>%
  ggplot(aes(x = A6, fill = A3)) +
  geom_bar(position = "fill") +
  labs(x = "Nivel educativo", y = "Proporción", fill = "Estrato") +
  ggtitle("Relación \n Estrato y Nivel Educativo") +
  papaja::theme_apa() +
  coord_flip() +
  scale_fill_manual(values = custom_palette)
plot_est_edu

plot_est_edu_2 <- data1 %>%
  ggplot(aes(x = A3, fill = A6)) +
  geom_bar(position = "fill") +
  labs(x = "Estrato", y = "Proporción", fill = "Nivel Educativo") +
  ggtitle("Relación \n Estrato y Nivel Educativo") +
  papaja::theme_apa() +
  scale_fill_manual(values = custom_palette)
plot_est_edu_2
```

```{r relaciones entre variables categóricas}
# Convert data frame to a list of ggplot objects
plots <- lapply(names(data), function(var) {
  ggplot(data, aes(x = .data[[var]], fill = .data[[var]])) +
    geom_bar() +
    labs(x = var, y = "Count") +
    theme_minimal()
})

# Combine the plots into a grid
grid <- plot_grid(plotlist = plots, nrow = 2, ncol = 2)

# Display the grid of plots
grid
```


