---
title: 'Encuesta: Propuestas de artículo'
author: "Juan Sebastian Cely"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
stopifnot(require(openxlsx), require(kableExtra), require(dm), require(dplyr), require (ggplot2), require(rms), require(caret), require(lmtest), require(car), require(yardstick), require(papaja), require(pandoc), require(tinytex), require(RColorBrewer), require(ggplotify), require(FactoMineR), require(factoextra), require(Factoshiny), require(effectsize))
knitr::opts_chunk$set(cache=F,fig.path="./figures",cache.rebuild = F, out.width = "80%")
options(knitr.table.format = "simple")
```

# Propuestas de artículo
A partir de lo encontrado en los análisis exploratorios y siguiendo criterios tanto estadísticos como basados en la revisión de literatura, se tienen dos propuestas de artículo.

## Emociones, conocimiento y acciones individuales contra el cambio climático

¿La valencia emocional ligada al conocimiento sobre el cambio climático tiene un impacto sobre la disposición a llevar a cabo acciones individuales contra el cambio climático en jovenes colombianos?

Hipótesis 1: Estar bien informado frente a las causas del cambio climático está relacionado con una mayor disposición a llevar a cabo acciones individuales contra el cambio climático en jovenes colombianos.

Hipótesis 2: Experimentar emociones negativas frente al cambio climático se relaciona con una mayor disposición a llevar a cabo acciones individuales contra el cambio climático en jovenes colombianos.

Hipótesis 3: Un joven colombiano bien informado que experimente emociones negativas hacia el cambio climático tiene mayor disposición a llevar a cabo acciones individuales contra el cambio climático. Por tanto, hay una interacción entre el conocimiento y la valencia emocional frente al cambio climático.

Si las hipótesis se confirman, quiere decir que tanto el conocimiento como las emociones que se transmiten son relevantes a la hora de buscar promover que los jovenes colombianos tomen acciones individuales contra el cambio climático.

Artículos de referencia:
[Brosch, T. (2021). Affect and emotions as drivers of climate change perception and action: a review. Current Opinion in Behavioral Sciences, 42, 15–21. doi:10.1016/j.cobeha.2021.02.001](https://www.sciencedirect.com/science/article/pii/S2352154621000206)
[Ogunbode, Charles & Doran, Rouven & Hanss, Daniel & Ojala, Maria & Salmela-Aro, Katariina & van den Broek, Karlijn & Bhullar, Navjot & Aquino, Sibele & Marot, Tiago & Schermer, Julie & Wlodarczyk, Anna & Lu, Su & Jiang, Feng & Acquadro Maran, Daniela & Yadav, Radha & Ardi, Rahkman & Chegeni, Razieh & Ghanbarian, Elahe & Zand, Somayeh & Lomas, Michael. (2022). Climate anxiety, pro-environmental action and wellbeing: antecedents and outcomes of negative emotional responses to climate change in 28 countries. 10.31219/osf.io/yn6tc.](https://www.researchgate.net/publication/357985350_Climate_anxiety_pro-environmental_action_and_wellbeing_antecedents_and_outcomes_of_negative_emotional_responses_to_climate_change_in_28_countries)
[Pihkala P (2022) Toward a Taxonomy of Climate Emotions. Front. Clim. 3:738154. doi: 10.3389/fclim.2021.738154](https://www.frontiersin.org/articles/10.3389/fclim.2021.738154/full)
[Ágoston, Csilla & Csaba, Benedek & Bence, Nagy & Kőváry, Zoltán & Dúll, Andrea & Rácz, József & Demetrovics, Zsolt. (2022). Identifying Types of Eco-Anxiety, Eco-Guilt, Eco-Grief, and Eco-Coping in a Climate-Sensitive Population: A Qualitative Study. International Journal of Environmental Research and Public Health. 19. 2461. 10.3390/ijerph19042461.](https://www.researchgate.net/publication/358777496_Identifying_Types_of_Eco-Anxiety_Eco-Guilt_Eco-Grief_and_Eco-Coping_in_a_Climate-Sensitive_Population_A_Qualitative_Study)
[Jain, Nishtha & Jain, Prashasti. (2022). Eco-Anxiety and Environmental Concern as Predictors of Eco-Activism. IOP Conference Series: Earth and Environmental Science. 1084. 012007. 10.1088/1755-1315/1084/1/012007.](https://www.researchgate.net/publication/364544298_Eco-Anxiety_and_Environmental_Concern_as_Predictors_of_Eco-Activism)
[Kurth C and Pihkala P (2022) Eco-anxiety: What it is and why it matters. Front. Psychol. 13:981814. doi: 10.3389/fpsyg.2022.981814](https://www.frontiersin.org/articles/10.3389/fpsyg.2022.981814/full)
[Schneider, C. R., Zaval, L., & Markowitz, E. M. (2021). Positive emotions and climate change. Current Opinion in Behavioral Sciences, 42, 114–120. doi:10.1016/j.cobeha.2021.04.009](https://www.sciencedirect.com/science/article/abs/pii/S2352154621000942)
[Hornsey, M., Harris, E., Bain, P. et al. Meta-analyses of the determinants and outcomes of belief in climate change. Nature Clim Change 6, 622–626 (2016). https://doi.org/10.1038/nclimate2943](https://www.nature.com/articles/nclimate2943)
[Kolenatý, Miloslav & Kroufek, Roman & Cincera, Jan. (2022). What Triggers Climate Action: The Impact of a Climate Change Education Program on Students’ Climate Literacy and Their Willingness to Act. Sustainability. 14. 10365. 10.3390/su141610365.](https://www.researchgate.net/publication/362845483_What_Triggers_Climate_Action_The_Impact_of_a_Climate_Change_Education_Program_on_Students'_Climate_Literacy_and_Their_Willingness_to_Act)
[Vainio, Annukka & Paloniemi, Riikka. (2013). Does Belief Matter in Climate Change Action?. Public understanding of science (Bristol, England). 22. 382-95. 10.1177/0963662511410268.](https://www.researchgate.net/publication/247157982_Does_Belief_Matter_in_Climate_Change_Action)
[Yilmaz, Veysel & Can, Yasemin. (2020). Impact of knowledge, concern and awareness about global warming and global climatic change on environmental behavior. Environment, Development and Sustainability. 22. 10.1007/s10668-019-00475-5.](https://www.researchgate.net/publication/336100230_Impact_of_knowledge_concern_and_awareness_about_global_warming_and_global_climatic_change_on_environmental_behavior)


## Relación entre el uso de internet y el conocimiento sobre el cambio climático

¿Los jovenes colombianos que se informan a través de internet tienden a estar peor informados sobre el cambio climático?

Hipótesis 1: Los jovenes colombianos que utilizan internet como fuente de información tienden a estar mejor informados sobre las causas del cambio climático.

Si la hipótesis se confirma, quiere decir que a pesar del aumento de las fake news compartidas en medios digitales y redes sociales, los jóvenes colombianos que se informan a través de estos medios tienden a estar mejor informados que aquellos que se informan a través de medios más tradicionales.

Artículos de referencia:
[Rosenthal, Sonny. (2022). Information sources, perceived personal experience, and climate change beliefs. Journal of Environmental Psychology. 81. 101796. 10.1016/j.jenvp.2022.101796.](https://www.researchgate.net/publication/359508624_Information_sources_perceived_personal_experience_and_climate_change_beliefs)
[Shaheen Ali, Zarqa. 2021. "New Media: A Game Changer for Climate Change and Natural Hazards." The International Journal of Climate Change: Impacts and Responses 13 (2): 179-195. doi:10.18848/1835-7156/CGP/v13i02/179-195.](https://www.cgscholar.com/bookstore/works/new-media-a-game-changer-for-climate-change-and-natural-hazards?category_id=cgrn&path=cgrn%2F192%2F193)