---
title: 'Encuesta: Relaciones entre variables'
author: "Juan Sebastian Cely"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
stopifnot(require(openxlsx), require(kableExtra), require(dm), require(dplyr), require (ggplot2), require(rms), require(caret), require(lmtest), require(car), require(yardstick), require(papaja), require(pandoc), require(tinytex), require(RColorBrewer), require(ggplotify), require(FactoMineR), require(factoextra))
knitr::opts_chunk$set(cache=F,fig.path="./figures",cache.rebuild = F, out.width = "80%")
options(knitr.table.format = "simple")
```

```{r data, include=FALSE}
wb<-loadWorkbook("020-22 Base de Datos Anonimizada V4 (1).xlsx")
names(wb)
data1 <- readWorkbook(wb,sheet=1)
codeBook1 <- readWorkbook(wb,sheet=2,skipEmptyRows = F)
```

```{r tranformación y recodificación variables, include=FALSE}
# Eco-anxiety
neg_emo <- c("C36_1", "C36_3", "C36_4", "C36_5", "C36_6", "C36_7", "C36_8", "C36_9", "C36_10", "C36_11", "C36_15")
amb_emo <- c("C36_13")
pos_emo <- c("C36_2", "C36_12", "C36_14", "C36_16")
data1$eco_anx <- NA
for (i in 1:nrow(data1)) {
neg_emo_count <- sum(data1[i, neg_emo] == 1)
pos_emo_count <- sum(data1[i, pos_emo] == 1)
amb_emo_count <- sum(data1[i, amb_emo] == 1)
if (neg_emo_count %in% c(1, 2) & pos_emo_count == 0 & amb_emo_count == 0) {
data1$eco_anx[i] <- "Con eco-ansiedad"
} else if (neg_emo_count == 1 & pos_emo_count == 1 & amb_emo_count == 0) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 1 & pos_emo_count == 0 & amb_emo_count == 1) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 0 & pos_emo_count == 1 & amb_emo_count == 1) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 0 & pos_emo_count == 0 & amb_emo_count == 1) {
data1$eco_anx[i] <- "Ambivalente/Neutral"
} else if (neg_emo_count == 0 & pos_emo_count %in% c(1, 2) & amb_emo_count == 0) {
data1$eco_anx[i] <- "Sin eco-ansiedad"
}
}
data1$eco_anx <- factor(data1$eco_anx, levels = c("Con eco-ansiedad", "Ambivalente/Neutral", "Sin eco-ansiedad"))

# Residential area
data1$Zona <- as.factor(data1$Zona)

# Sex
data1$A1 <- as.factor(data1$A1)
levels(data1$A1) <- c("Hombre", "Mujer")
data1$sex <- data1$A1

# Age range
data1$RANGO_EDAD <- as.factor(data1$RANGO_EDAD)
data1$age_r <- data1$RANGO_EDAD
data1 <- data1 %>%
  mutate(age_r = case_when(
    age_r == 1 ~ "De 18 a 20 años",
    age_r == 2 ~ "De 21 a 24 años",
    age_r == 3 ~ "De 25 a 29 años",
    age_r == 4 ~ "De 30 a 32 años"
))
data1$age_r <- as.factor(data1$age_r)

# Stratum
data1$A3 <- as.factor(data1$A3)
data1$strat <- data1$A3
data1 <- data1 %>%
  mutate(strat = case_when(
    strat %in% c(1,2) ~ "Bajo",
    strat %in% c(3,4) ~ "Medio",
    strat %in% c(5,6) ~ "Alto"
))
data1$strat <- factor(data1$strat, levels = c("Bajo", "Medio", "Alto"))

# Ethnics
data1$ethni <- data1$A5
data1 <- data1 %>%
  mutate(ethni = case_when(
    ethni != "Ninguna" ~ "Sí",
    ethni == "Ninguna" ~ "No"
))
data1$ethni <- as.factor(data1$ethni)

# Education
data1$A6 <- as.factor(data1$A6)
levels(data1$A6) <- c("Básica Primaria", "Básica Secundaria", "Secundaria Completa", "Técnico o Tecnólogo", "Pregrado", "Posgrado")
data1$edu <- data1$A6
data1 <- data1 %>%
  mutate(edu = case_when(
    edu %in% c("Básica Primaria", "Básica Secundaria", "Secundaria Completa", "Técnico o Tecnólogo") ~ "No",
    edu %in% c("Pregrado", "Posgrado") ~ "Sí"
))
data1$edu <- as.factor(data1$edu)

# Kids
data1$A9 <- as.factor(data1$A9)
levels(data1$A9) <- c("Sí", "No")
data1$kids <- data1$A9

# Political ideology
data1$A11 <- as.factor(data1$A11)
data1 <- data1 %>%
  mutate(ideology = case_when(
    A11 %in% c(1, 2) ~ "Izquierda",
    A11 %in% c(3, 4) ~ "Centro",
    A11 %in% c(5, 6) ~ "Derecha"
  ))
data1$ideology <- factor(data1$ideology, levels = c("Derecha", "Centro", "Izquierda"))

# Information sources
media <- grep("^B12_", names(data1), value = TRUE)
data1 <- data1 %>%
  mutate(across(all_of(media), ~ factor(., levels = c("No", "Sí")))) %>%
  rename(Televisión = B12_1,
         Radio = B12_2,
         Prensa_Impresa = B12_3,
         Medios_Digitales = B12_4,
         Redes_Sociales = B12_5,
         Otro_medio = B12_89)

# Trust in particular Institutions and figures
trust_vote_inst <- data1 %>%
  select(C17_5, C17_7, C17_8)
trust_vote_inst[] <- lapply(trust_vote_inst, function(x) replace(x, x == 2, -1))
trust_vote_inst[] <- lapply(trust_vote_inst, function(x) replace(x, x == 3, 0))
data1$trust_vote_inst <- rowSums(trust_vote_inst)

trust_unis <- data1 %>%
  select(C17_14, C17_15)
trust_unis[] <- lapply(trust_unis, function(x) replace(x, x == 2, -1))
trust_unis[] <- lapply(trust_unis, function(x) replace(x, x == 3, 0))
data1$trust_unis <- rowSums(trust_unis)

# Join an environmental organization
data1$C18_7 <- as.factor(data1$C18_7)
levels(data1$C18_7) <- c("Sí", "No")
data1$env_aso <- data1$C18_7

# Negative emotions towards actions taken by the government regarding climate change
neg_d34 <- c("D34_2", "D34_3", "D34_4", "D34_6", "D34_8", "D34_9")
pos_d34 <- c("D34_1", "D34_5", "D34_7", "D34_10")
data1$neg_emo_gov <- NA
for (i in 1:nrow(data1)) {
  data1$neg_emo_gov[i] <- sum(data1[i, neg_d34]) - sum(data1[i, pos_d34]) + 19
}

# Impact of scientists on climate change
data1$imp_scien <- data1$D35_1
data1$imp_scien[data1$imp_scien == 99] <- 3.5
value_mapping <- c(1, 2, 3, 3.5, 4, 5, 6)
new_values <- c(-3, -2, -1, 0, 1, 2, 3)
data1$imp_scien <- new_values[match(data1$imp_scien, value_mapping)]
data1$imp_scien <- as.factor(data1$imp_scien)

# Impact of activists on climate change
data1$imp_act <- data1$D35_7
data1$imp_act[data1$imp_act == 99] <- 3.5
value_mapping <- c(1, 2, 3, 3.5, 4, 5, 6)
new_values <- c(-3, -2, -1, 0, 1, 2, 3)
data1$imp_act <- new_values[match(data1$imp_act, value_mapping)]
data1$imp_act <- as.factor(data1$imp_act)

# Impact of religious groups on climate change
data1$imp_rel <- data1$D35_3
data1$imp_rel[data1$imp_rel == 99] <- 3.5
value_mapping <- c(1, 2, 3, 3.5, 4, 5, 6)
new_values <- c(-3, -2, -1, 0, 1, 2, 3)
data1$imp_rel <- new_values[match(data1$imp_rel, value_mapping)]
data1$imp_rel <- as.factor(data1$imp_rel)

# Impact of politicians on climate change
data1$imp_pol <- data1$D35_6
data1$imp_pol[data1$imp_pol == 99] <- 3.5
value_mapping <- c(1, 2, 3, 3.5, 4, 5, 6)
new_values <- c(-3, -2, -1, 0, 1, 2, 3)
data1$imp_pol <- new_values[match(data1$imp_pol, value_mapping)]
data1$imp_pol <- as.factor(data1$imp_pol)

# Thoughts about climate change
pos_thought <- c("C37_9", "C37_11", "C37_12", "C37_13", "C37_15")
neg_thought<- c("C37_1", "C37_2", "C37_4", "C37_5", "C37_6", "C37_7", "C37_8", "C37_14")
neut_thought <- c("C37_3", "C37_10")
data1$thoughts <- NA
for (i in 1:nrow(data1)) {
neg_th_count <- sum(data1[i, neg_thought] == 1)
pos_th_count <- sum(data1[i, pos_thought] == 1)
amb_th_count <- sum(data1[i, neut_thought] == 1)
if (neg_th_count %in% c(1, 2, 3) & pos_th_count == 0 & amb_th_count == 0) {
data1$thoughts[i] <- "Negativos"
} else if (neg_th_count == 2 & pos_th_count == 1 & amb_th_count == 0) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 2 & pos_th_count == 0 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 1 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 1 & amb_th_count == 0) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 0 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count %in% c(1, 2, 3) & amb_th_count == 0) {
data1$thoughts[i] <- "Positivos"
} else if (neg_th_count == 1 & pos_th_count == 2 & amb_th_count == 0) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 2 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 1 & amb_th_count == 1) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 0 & amb_th_count %in% c(1, 2)) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 1 & pos_th_count == 0 & amb_th_count == 2) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
} else if (neg_th_count == 0 & pos_th_count == 1 & amb_th_count == 2) {
data1$thoughts[i] <- "Ambivalentes/Neutrales"
}
}
data1$thoughts <- factor(data1$thoughts, levels = c("Negativos", "Ambivalentes/Neutrales", "Positivos"))

# Impact of individual actions on comfort
c38 <- grep("^C38_", names(data1), value=T)
data1$imp_como <- NA
for (i in 1:nrow(data1)) {
  data1$imp_como[i] <- sum(data1[i, c38]) / 10 - 3.5
}

# Impact of individual actions on climate change
c39 <- grep("^C39_", names(data1), value=T)
data1$imp_cli <- NA
for (i in 1:nrow(data1)) {
  data1$imp_cli[i] <- sum(data1[i, c39]) / 10 - 3.5
}

# Climate change origin
data1$C40 <- as.factor(data1$C40)
data1 <- data1 %>%
  mutate(clim_origin = case_when(
    C40 %in% c(1,2,3,4,5,6,7) ~ "Incorrecta",
    C40 %in% c(8,9,10) ~ "Correcta"
    ))
data1$clim_origin <- as.factor(data1$clim_origin)

# Contribution to climate change
data1$C41 <- as.factor(data1$C41)
data1 <- data1 %>%
  mutate(cont_clim = case_when(
    C41 %in% c(1, 3, 4) ~ "Incorrecta",
    C41 == 2 ~ "Correcta"
))
data1$cont_clim <- as.factor(data1$cont_clim)
```

```{r data frames para variables continuas y variables categoricas, include=FALSE}
data2 <- data1 %>%
  select(eco_anx, Zona, sex, age_r, strat, ethni, A6, edu, kids, ideology, Televisión, Radio, Prensa_Impresa, Medios_Digitales, Redes_Sociales, Otro_medio, trust_vote_inst, trust_unis, env_aso, neg_emo_gov, imp_scien, imp_act, imp_rel, imp_pol, thoughts, imp_como, imp_cli, clim_origin, cont_clim)

data_cont <- data2 %>%
  select(trust_vote_inst, trust_unis, neg_emo_gov, imp_como, imp_cli)

data_cat <- data2 %>%
  select(eco_anx, Zona, sex, age_r, strat, ethni, A6, edu, kids, ideology, Televisión, Radio, Prensa_Impresa, Medios_Digitales, Redes_Sociales, Otro_medio, env_aso, imp_scien, imp_act, imp_rel, imp_pol, thoughts, clim_origin, cont_clim)
```


```{r analisis de variables continuas, include=FALSE}
# Correlation matrix
cor_matrix <- round(cor(data_cont), 2)
kable(cor_matrix)
```


```{r análisis de componentes múltiples}
chisq.test(data1_cat$eco_anx, data1_cat$clim_origin)
result_mca <- MCA(data1_cat, graph = TRUE)
res.mca <- MCA(data1_cat, graph = FALSE)
fviz_mca_biplot(res.mca, 
               repel = TRUE,
               ggtheme = theme_minimal())
```

# Emociones frente al cambio climático y zona de residencia

```{r relación estrato edad}
tab_est_age <- table(data1$age_r, data1$A3)
kable(round(prop.table(tab_est_age) * 100, 1), booktabs = TRUE)

custom_palette <- brewer.pal(6, "Set2")
plot_est_age <- data1 %>%
  ggplot(aes(x = strat, y = A2)) +
  geom_boxplot(aes(colour = strat)) +
  labs(x = "Estrato", y = "Edad") +
  ggtitle("Distribución \n Edad por Estrato") +
  papaja::theme_apa() +
  scale_y_continuous(breaks = seq(18, 32, 2)) +
  theme(legend.position="none") +
  scale_color_manual(values = custom_palette)
plot_est_age
```


```{r relación nivel educativo estrato}
tab_est_edu <- table(data1$A6, data1$A3)
kable(round(prop.table(tab_est_edu) * 100, 1), booktabs = TRUE)

custom_palette <- brewer.pal(6, "BrBG")
plot_est_edu <- data1 %>%
  ggplot(aes(x = A6, fill = A3)) +
  geom_bar(position = "fill") +
  labs(x = "Nivel educativo", y = "Proporción", fill = "Estrato") +
  ggtitle("Relación \n Estrato y Nivel Educativo") +
  papaja::theme_apa() +
  coord_flip() +
  scale_fill_manual(values = custom_palette)
plot_est_edu

plot_est_edu_2 <- data1 %>%
  ggplot(aes(x = A3, fill = A6)) +
  geom_bar(position = "fill") +
  labs(x = "Estrato", y = "Proporción", fill = "Nivel Educativo") +
  ggtitle("Relación \n Estrato y Nivel Educativo") +
  papaja::theme_apa() +
  scale_fill_manual(values = custom_palette)
plot_est_edu_2
```

```{r relaciones entre variables categóricas}
# Convert data frame to a list of ggplot objects
plots <- lapply(names(data), function(var) {
  ggplot(data, aes(x = .data[[var]], fill = .data[[var]])) +
    geom_bar() +
    labs(x = var, y = "Count") +
    theme_minimal()
})

# Combine the plots into a grid
grid <- plot_grid(plotlist = plots, nrow = 2, ncol = 2)

# Display the grid of plots
grid
```


